# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 09:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2017, 12, 18, 9, 51, 19, 425371, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 18, 9, 51, 19, 425302, tzinfo=utc)),
        ),
    ]
