# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 23:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171218_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2017, 12, 18, 23, 18, 14, 226489, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 18, 23, 18, 14, 226417, tzinfo=utc)),
        ),
    ]
